[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, s-maxage=900, stale-while-revalidate=1800"
